name: Release vectors

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          architecture: 'x64'
      - name: Cache pip
        uses: actions/cache@v3
        with:
          # This path is specific to Ubuntu
          path: ~/.cache/pip
          # Look to see if there is a cache hit for the corresponding requirements file
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            ${{ runner.os }}-
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          make install_ci
      - name: Run the generator with JSON output
        run: make generate_json
      - name: Run the generator with YAML output
        run: make generate_yaml
      - name: Upload generator output as artifact
        uses: actions/upload-artifact@v4
        with:
          name: test-vectors
          path: out
          retention-days: 3
        # Unlike regular python build flow, we do not store test vectors if the build failed,
        # to avoid bad release output.
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Take the generated test vectors
        uses: actions/download-artifact@v2
        with:
          name: test-vectors
          path: out
      - name: Display file structure
        run: ls -R
      - name: Prepare release
        run: |
          tar -czvf bls_tests_json.tar.gz -C out/json/bls .
          tar -czvf bls_tests_yaml.tar.gz -C out/yaml/bls .
      # see https://github.com/softprops/action-gh-release
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            bls_tests_json.tar.gz
            bls_tests_yaml.tar.gz
